### ISSUE TITLE
In grid view when there are more than 7 rows of games, view jerks up and down while scrolling

### ISSUE THREAD

**Issue by jroyvde** [RBertoCases/skylineOS#12] opened 2021-07-17 01:10 UTC
skylineOS version 0.8
Pegasus version 0.15 Alpha 15
Pop!_OS 21.04 with GNOME 3.38

View seems to jerk suddenly when scrolling vertically in the grid-style view. Doesn't cause any functional issues, but is very disorienting. Seems to be 100% reproducible at resolutions of 2560x1440 and 1280x720, does not occur at all when I change my display settings to 1920x1080.

Happens only in the grid view, and only when there are more than 7 rows of games in the collection (more than 42 games). Because of this, it's easiest to reproduce in the 'All Software' view if you have enough games.

Hard to describe properly in words so I made a video to demonstrate the issue. The video is of switchOS, and I recorded it some time ago to report the issue there - however the original project doesn't seem to be maintained any more so I figure it's more likely to get a fix here.

https://user-images.githubusercontent.com/54386705/126020911-10a824bd-cf69-42f9-8047-3d17a2170f07.mp4

**Comment by RBertoCases** [comment] 2021-07-20 01:07
Yeah, I'm able to reproduce it those 2 resolutions. I'll look into a solution.

**Comment by RBertoCases** [comment] 2021-07-20 01:35
@jroyvde I think I may have fixed the issue by changing the following property in SoftwareScreen from `snapMode: ListView.SnapToItem' to 'snapMode: ListView.NoSnap' I committed the change to my dev branch. Could you test it and report back if that works for you? And if works, you could make the same change to your local copy of switchOS.
Thanks!

**Closed** 2021-07-21 04:01 UTC
Labels: bug

**Comment by RBertoCases** [comment] 2021-07-21 04:03
It works in my testing so I went ahead and merged it into the main branch. if you grab v0.9.2 or later, it will have the change.

**Comment by jroyvde** [comment] 2021-07-21 12:15
The situation seems much improved, but the underlying issue's still hanging on, unfortunately. The experience of scrolling downward seems pretty seamless now, but going up again is another story. There also still seems to be that small 'bump' at the very beginning, when scrolling down for the first time.

https://user-images.githubusercontent.com/54386705/126486742-de805dd5-2f08-4751-9468-b2a7d47fa75f.mp4

**Comment by RBertoCases** [comment] 2021-07-21 19:24
I can probably fix the bump at the very beginning. I think that may be caused by what I set the top margin to and adding word wrap to the titles. I'm not sure about the jerkiness of going up. I noticed that too and I'm not sure what properties to mess with to alter that, but I'll look into it.

**Comment by RBertoCases** [comment] 2021-07-21 22:19
@jroyvde Try making this change under software screen and see if that works for you.
from: highlightRangeMode: ListView.StrictlyEnforceRange
to: highlightRangeMode: ListView.ApplyRange

The big issue is that is slightly breaks mouse navigation as the highlight no longer follows the view, but it works fine for gamepad/keyboard navigation and may work for your needs. But since it breaks mouse navigation, I probably won't commit it any time soon.

**Comment by jroyvde** [comment] 2021-07-22 00:19
Yep, I can confirm that change completely solves the problem! (Even though it does create new problems with mouse navigation.) Totally fine for my individual needs, though, as I only navigate Pegasus with a keyboard or gamepad anyways. Strange issue though, I wonder why it's only certain display resolutions that trigger it.
